# Generated by Django 6.1 on 2026-10-07 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('efectos', models.JSONField(blank=True, null=True)),
                ('costo', models.JSONField(blank=True, null=True)),
                ('kit_inicial', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_compra', models.PositiveIntegerField(default=10)),
                ('precio_venta', models.PositiveIntegerField(default=5)),
                ('efectos', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='objetos/')),
                ('es_equipable', models.BooleanField(default=False)),
                ('tipo_equipamiento', models.CharField(blank=True, choices=[('arma', 'Arma'), ('casco', 'Casco'), ('armadura', 'Armadura'), ('zapatos', 'Zapatos'), ('collar', 'Collar'), ('brazalete', 'Brazalete'), ('escudo', 'Escudo')], max_length=20, null=True)),
                ('kit_inicial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('r_bonificadores', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('img_body', models.ImageField(upload_to='razas/body/')),
                ('img_head', models.ImageField(upload_to='razas/head/')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.objeto')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('congelado', 'Congelado')], default='vivo', max_length=50)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('oro', models.PositiveIntegerField(default=0)),
                ('exp_siguiente_nivel', models.PositiveIntegerField(default=100)),
                ('hp_base', models.PositiveIntegerField(default=100)),
                ('hp_actual', models.IntegerField(default=100)),
                ('mana_base', models.PositiveIntegerField(default=50)),
                ('mana_actual', models.IntegerField(default=50)),
                ('activo', models.BooleanField(default=True)),
                ('arma_equipada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_arma', to='gestion.objeto')),
                ('armadura_equipada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_armadura', to='gestion.objeto')),
                ('brazalete_equipado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_brazalete', to='gestion.objeto')),
                ('casco_equipado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_casco', to='gestion.objeto')),
                ('collar_equipado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_collar', to='gestion.objeto')),
                ('escudo_equipado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_escudo', to='gestion.objeto')),
                ('habilidades', models.ManyToManyField(related_name='personajes', to='gestion.habilidad')),
                ('objetos', models.ManyToManyField(related_name='personajes', through='gestion.InventarioItem', to='gestion.objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
                ('zapatos_equipados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipada_como_zapatos', to='gestion.objeto')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personajes', to='gestion.raza')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.personaje'),
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuerza', models.PositiveIntegerField()),
                ('destreza', models.PositiveIntegerField()),
                ('vigor', models.PositiveIntegerField()),
                ('inteligencia', models.PositiveIntegerField()),
                ('percepcion', models.PositiveIntegerField()),
                ('carisma', models.PositiveIntegerField()),
                ('suerte', models.PositiveIntegerField()),
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='gestion.personaje')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventarioitem',
            unique_together={('personaje', 'objeto')},
        ),
    ]
