# Generated by Django 6.1 on 2026-10-07 02:50

import django.core.validators
from math import isqrt
from django.conf import settings
from django.db import migrations, models


def normalizar_progreso(apps, schema_editor):
    Personaje = apps.get_model('gestion', 'Personaje')
    alias = schema_editor.connection.alias
    for personaje in Personaje.objects.using(alias).all().iterator():
        nivel = max(1, personaje.nivel)
        total = max(0, personaje.experiencia) + 50 * nivel * (nivel - 1)
        personaje.nivel = (1 + isqrt(1 + 4 * (total // 50))) // 2
        personaje.experiencia = total - 50 * personaje.nivel * (personaje.nivel - 1)
        personaje.exp_siguiente_nivel = 100 * personaje.nivel
        personaje.save(using=alias, update_fields=['nivel', 'experiencia', 'exp_siguiente_nivel'])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='nivel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel mínimo'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nivel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        # La XP normalizada se conserva al revertir; recuperar respaldo para
        # restaurar exactamente la progresión anterior.
        migrations.RunPython(normalizar_progreso, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='objeto',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__gte', 1)), name='objeto_nivel_positivo'),
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__gte', 1)), name='personaje_nivel_positivo'),
        ),
    ]
